- name: Check for MiSTer.version
  ansible.builtin.stat:
    path: /MiSTer.version
  register: mister_version_exists

- name: Check for downloader.sh script
  ansible.builtin.stat:
    path: /media/fat/Scripts/downloader.sh
  register: mister_update_script_exists
  when:
    - mister_version_exists.stat.exists
    - updater_script == "downloader"

- name: Run update script
  ansible.builtin.raw: /media/fat/Scripts/downloader.sh
  check_mode: false
  changed_when: true
  ignore_errors: true
  register: mister_update_script_output
  when:
    - mister_version_exists.stat.exists
    - mister_update_script_exists.stat.exists

- name: Display update results
  ansible.builtin.debug:
    msg: "{{ mister_update_script_output.stdout_lines }}"
  when:
    - mister_version_exists.stat.exists
    - mister_update_script_exists.stat.exists

- name: Wait for the MiSTer to finish any needed reboot
  ansible.builtin.wait_for_connection:
    connect_timeout: 5
    sleep: 1
    timeout: 60
  when:
    - mister_version_exists.stat.exists
    - mister_update_script_exists.stat.exists
